from .agents import EMAIL_CATEGORIZER, EMAIL_WRITER
from .tasks import EMAIL_CATEGORIZER_TASK, EMAIL_WRITER_TASK

EMAIL_CATEGORIZER_PROMPT = f"{EMAIL_CATEGORIZER}\n{EMAIL_CATEGORIZER_TASK}"
EMAIL_WRITER_PROMPT = f"{EMAIL_WRITER}\n{EMAIL_WRITER_TASK}"